# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            The Archives
tagline:          'The MagicDuel Archives'
description:      'A repository of information containing the living history of MagicDuel'
url:              http://the-archives-underground.github.io

author:
  name:           'The Archivists and the MagicDuel Community'

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/the-archives-underground/the-archives-underground.github.io
